[settings]
pipx.uvx = true

[tools]
"github:peterldowns/localias" = "latest"
"jq" = "latest"

# packages that are *not* required for running the development server, tests, etc should be included here
"pipx:ruff" = "latest"
"pipx:squawk-cli" = "latest"
