[tools]
"github:peterldowns/localias" = "latest"
"jq" = "latest"
"mprocs" = "latest"
"fd" = "latest"
"yq" = "latest"
"watchexec" = "latest"
# great for docker image exploration
"dive" = "latest"
"cargo:just-lsp" = "latest"

# packages that are *not* required for running the development server, tests, build, etc should be included here
# uv provides two ways of managing tools: via `uv tool` and `uvx`. `uv tool` caches the tool in the local venv
# while `uvx` installs the tool globally. These pipx tools use `uvx` under the hood but the tools are not installed
# in the local venv, they are installed globally for the user, which is generally what we want for this class of dev-only
# CLI tools.
# TODO I've only partially migrated debugging-extras to this, need to finish
"pipx:aiautocommit" = "latest"

[env]
# add paths to override default tooling, helpful when hacking on a cli dependency
# note that this can be problematic if you have binaries which override with mise. Mise will most likely force its
# bin/ dirs for those binaries first.
# _.path = [
#     "~/Projects/go/localias/bin/",
#     "~/Projects/deployment/nixpacks/target/release/",
# ]
