# packages that are *not* required in production, but are required for development (and ci) should be included here

# - `pipx` mise backend actually installs tools via `uv tool install` which means the tool can be shared across projects
# - if a package requires access to the venv of the project itself, it should be in `dev` or `debugging-extras` if it's
#   only for local development/CI.

[tools]
"github:peterldowns/localias" = "latest"
"github:gitleaks/gitleaks" = "latest"
"jq" = "latest"
"mprocs" = "latest"
"fd" = "latest"
"yq" = "latest"
"watchexec" = "latest"

[env]
# add paths to override default tooling, helpful when hacking on a cli dependency
# note that this can be problematic if you have binaries which override with mise. Mise will most likely force its
# bin/ dirs for those binaries first.
# _.path = [
#     "~/Projects/go/localias/bin/",
#     "~/Projects/deployment/nixpacks/target/release/",
# ]
